- project-management:
  - .github/**/*
  - .gitignore
  - .prettier*
- documentation:
  - CONTRIBUTE/**/*
  - README.md
- auto-scripts:
  - scripts/**/*
- dependencies:
  - package.json
  - package-lock.json
- templates:
  - src/templates/**/*
- styling:
  - src/assets/css/**/*
- image-assets:
  - src/assets/images/**/*
- plugins-gatsby:
  - gatsby-*