
linkedin: company/ietnitk/

github: IET-NITK
instagram: ietnitk

permalink: /:title/
contactdetails:
  - name: Skanda
    phone: 9481141528
  - name: Palash 
    phone: 9870036171
contactemail: iet@nitk.ac.in

# Jekyll-SEO
title: IET NITK
tagline: Official Website of Insitute of Engineering and Technology, NITK Chapter
description: To inspire, inform and influence the global engineering community, supporting technology innovation to meet the needs of society.
url: https://iet-nitk.github.io/
author: IET NITK Web Team
facebook: ietnitk
logo: /assets/img/logo.png
social:
  links:
    - 
# the base hostname & protocol for your site
collections:
  authors:
recruitmentOpen: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - liquid_reading_time
  - liquid_pluralize
  - jekyll-admin
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-133733565-3          # Required - replace with your tracking id
    anonymizeIp: false 
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "blog-post"
  - scope:
      path: ""
    values:
      layout: "default"