title: IET NITK
linkedin: company/ietnitk/
facebook: ietnitk
github: IET-NITK
instagram: ietnitk
author: Nirmal Khedkar
description: To inspire, inform and influence the global engineering community, supporting technology innovation to meet the needs of society.

contactname: Name 1
contactemail: Email 1
contactphone: phone 1
url: "http://iet-nitk.github.io/newweb" # the base hostname & protocol for your site
collections:
  authors:
    output: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - liquid_reading_time
  - liquid_pluralize
  - jekyll-admin


defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "blog-post"
  - scope:
      path: ""
    values:
      layout: "default"