title: IET NITK
linkedin: company/ietnitk/
facebook: ietnitk
github: IET-NITK
instagram: ietnitk
author: Nirmal Khedkar
description: To inspire, inform and influence the global engineering community, supporting technology innovation to meet the needs of society.

contactname: Name 1
contactemail: Email 1
contactphone: phone 1
url: "http://iet-nitk.github.io/newweb" # the base hostname & protocol for your site
collections:
  authors:
    output: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-analytics
  - jekyll-feed
  - liquid_reading_time
  - liquid_pluralize
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: xxxx          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking