name: Deployment Workflow

on:
  push:
    branches:
      - daddy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install NPM Packages
        run: npm install
      - name: Set up git
        run: |
          git config --global user.email "iet@nitk.edu.in"
          git config --global user.name "IET NITK"
      # Runs a set of commands using the runners shell
      - name: Build script
        run: npm run build
      - name: Deploy script
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public