name: DnT Workflow

on:
  # Trigger the workflow on push or pull request,
  # but only for the daddy branch
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - daddy
  pull_request:
    branches:
      - daddy

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NPM Packages
        run: npm install
      # - name: Get secrets
      #   shell: bash
      #   env:
      #     BACKEND_TOKEN: ${{ secrets.BACKEND_TOKEN }}
      #   run: echo $BACKEND_TOKEN > credentials.json
      - name: Build script
        run: npm run build
      - name: Pass on build directory
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref=='refs/heads/daddy'
    steps:
      - name: Download hello world file
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public
      - name: Set up git
        run: |
          git config --global user.email "iet@nitk.edu.in"
          git config --global user.name "IET NITK"
      # Runs a set of commands using the runners shell
      - name: Deploy script
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          cname: iet.nitk.ac.in
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: Contributor Bot
    if: github.ref=='refs/heads/daddy'
    steps:
        - name: Contribute List
          uses: akhilmhdh/contributors-readme-action@v2.1.2
          env:
              GITHUB_TOKEN: ${{ secrets.IET_PAT }}
          with:
            columns_per_row: 5
